Repository Arquisoft/wiq_en3a, pull requests merged in 2024-03, with the labels that each got.

#88 Automatic Wikidata queries and suffling the correct answer
  wikidata_service/WikiDataTest/Controllers/WikiDataController.cs
  wikidata_service/WikiDataTest/Models/Question.cs
  wikidata_service/WikiDataTest/Services/QueryService.cs
Labels: Wikidata, API

#90 Changing API port
  docker-compose.yml
  wikidata_service/WikiDataTest/Dockerfile
Labels: API

#95 Merging user scores
  webapp/src/components/Game/Game.tsx
  webapp/src/components/general/Nav.tsx
  webapp/src/services/auth-service.ts
  webapp/src/stores/playing-store.ts
Labels: enhancement, Front-End

#103 Updating documentation
  docs/images/10-Quality-Tree-EN.png
  docs/src/04_solution_strategy.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation

#105 Changes in Dockerfile of wikidata
  wikidata_service/WikiDataTest/Dockerfile
Labels: Wikidata, API

#112 Deployment fixes
  gatewayservice/gateway-service.js
  webapp/src/stores/playing-store.ts
Labels: deployment

#122 Release improves
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/gateway-service.js
  gatewayservice/openapi.yaml
  users/Dockerfile
  users/userservice/Dockerfile
  webapp/.env
  webapp/Dockerfile
  webapp/src/services/auth-service.ts
  webapp/src/stores/playing-store.ts
  wikidata_service/Dockerfile
  wikidata_service/WikiDataTest/Properties/launchSettings.json
Labels: deployment
