Repository Arquisoft/wiq_en3a, pull requests merged in 2024-04, with the labels that each got.

#150 Added some links in the README
  README.md
Labels: documentation

#154 /login userservice tests
  users/authservice/auth-service.test.js
  users/authservice/package-lock.json
  users/authservice/package.json
  users/index.js
Labels: Testing

#158 OpenAPI for wikidata part
  gatewayservice/openapi.yaml
Labels: documentation, API

#164 Documentation sergiot
  docs/src/04_solution_strategy.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation

#167 Deploymeny issue
  docker-compose.yml
  gatewayservice/gateway-service.js
  users/index.js
  users/userservice/Dockerfile
  wikidataservice/index.js
Labels: deployment

#193 Leaderboard page - Rita
  gatewayservice/gateway-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/general/SimpleNav.tsx
  webapp/src/components/leaderboard/LeaderBoard.tsx
  webapp/src/components/leaderboard/RankingTable.tsx
  webapp/src/index.css
  webapp/src/services/auth-service.ts
Labels: Front-End

#196 Leaderboard and questions fix
  webapp/src/components/leaderboard/RankingTable.tsx
  wikidataservice/src/Models/Question-Model.json
  wikidataservice/src/Services/QueryGenerator.js
  wikidataservice/src/Services/QuestionGenerator.js
Labels: bug, Wikidata, API

#198 Test gateway fixed
  api/package-lock.json
  gatewayservice/gateway-service.test.js
Labels: Testing

#200 Trivia improvements
  webapp/src/components/Game/Game.test.tsx
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Game/GameOver.test.tsx
  webapp/src/components/Game/GameOver.tsx
  webapp/src/components/Game/Trivia/TriviaGame.tsx
  webapp/src/components/Game/Trivia/TriviaQuestion.tsx
  webapp/src/components/Game/Trivia/categories.ts
Labels: enhancement

#212 Open api new endpoints documented
  gatewayservice/openapi.yaml
Labels: Wikidata, API

#242 Updating the whole documenation
  .github/workflows/release.yml
  README.md
  docker-compose.yml
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_system_scope_and_context.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
  users/index.js
  webapp/Dockerfile
  webapp/e2e/jest.config.js
  webapp/e2e/steps/leaderboard.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/logout.steps.js
  webapp/e2e/steps/normal-game.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/steps/statistics.steps.js
  webapp/e2e/steps/trivia-game.steps.js
  webapp/package-lock.json
  webapp/package.json
  wikidataservice/index.js
Labels: documentation

#245 Readme update
  README.md
Labels: documentation
