Repository Arquisoft/wiq_en3a, pull requests merged in 2024-02, with the labels that each got.

#2 Readme modification with team members
  README.md
Labels: documentation

#12 Solution strategy documentation
  docs/src/04_solution_strategy.adoc
  docs/src/12_glossary.adoc
Labels: documentation

#11 Block View Initial Approach
  docs/package-lock.json
  docs/package.json
  docs/src/05_building_block_view.adoc
  package-lock.json
Labels: documentation

#15 Deleting <> on titles
  docs/src/06_runtime_view.adoc
Labels: bug, documentation

#22 Documentation vira
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#32 Improvement of the ReadMe
  README.md
Labels: documentation

#35 Section 11
  docs/src/11_technical_risks.adoc
Labels: documentation

#55 Fixed error position DB
  docs/src/06_runtime_view.adoc
Labels: documentation, Change needed

#57 Badges in ReadMe
  README.md
Labels: documentation

#70 Documentation improvements Vira
  docs/src/01_introduction_and_goals.adoc
Labels: documentation
